FROM sbtscala/scala-sbt:eclipse-temurin-alpine-21.0.6_7_1.10.10_3.6.3

WORKDIR /app

COPY . /app

RUN sbt clean compile assembly

ENTRYPOINT ["java", "-Xms400M", "-Xmx400M", "-jar", "api/target/scala-3.6.3/api-assembly-0.1.0-SNAPSHOT.jar"]
