FROM sbtscala/scala-sbt:eclipse-temurin-alpine-21.0.6_7_1.10.10_3.6.3

WORKDIR /app

COPY . /app

ENV SBT_OPTS="-Xms256M -Xmx256M"

RUN sbt clean compile

ENTRYPOINT ["sbt", "; project backend; run"]
