FROM sbtscala/scala-sbt:eclipse-temurin-alpine-21.0.6_7_1.10.10_3.6.3

WORKDIR /app

COPY . /app

ENV SBT_OPTS="-Xms256M -Xmx256M"

RUN sbt clean compile assembly

ENTRYPOINT ["java", "-Xms400M", "-Xmx400M", "-jar", "backend/target/scala-3.6.3/backend-assembly-0.1.0-SNAPSHOT.jar"]
