create table if not exists event (
    id bigint generated always as identity,
    name varchar(255) not null,
    sex varchar(255) not null,
    event varchar(255) not null,
    equipment varchar(255) not null,
    age numeric(4, 1),
    age_class varchar(255),
    birth_year_class varchar(255),
    division varchar(255),
    bodyweight_kg numeric(5, 2),
    weight_class_kg varchar(255),
    squat_1_kg numeric(5, 2),
    squat_2_kg numeric(5, 2),
    squat_3_kg numeric(5, 2),
    squat_4_kg numeric(5, 2),
    best_3_squat_kg numeric(5, 2),
    bench_1_kg numeric(5, 2),
    bench_2_kg numeric(5, 2),
    bench_3_kg numeric(5, 2),
    bench_4_kg numeric(5, 2),
    best_3_bench_kg numeric(5, 2),
    deadlift_1_kg numeric(5, 2),
    deadlift_2_kg numeric(5, 2),
    deadlift_3_kg numeric(5, 2),
    deadlift_4_Kg numeric(5, 2),
    best_3_deadlift_kg numeric(5, 2),
    total_kg numeric(6, 2),
    place varchar(255) not null,
    dots numeric(5, 2),
    wilks numeric(5, 2),
    glossbrenner numeric(5, 2),
    goodlift numeric(5, 2),
    tested boolean,
    country varchar(255),
    state varchar(255),
    federation varchar(255) not null,
    parent_federation varchar(255),
    date date not null,
    meet_country varchar(255) not null,
    meet_state varchar(255),
    meet_town varchar(255),
    meet_name varchar(255) not null,
    sanctioned boolean,
    primary key(id)
);

create materialized view vw_event AS 
SELECT * 
FROM event;
